// Forced deep re-scan of HIDDEN-ORIGIN hot leads (cloud = cloudflare/other/unknown) for Alto+Novalo.
// Calls the live cloud-detect ADHOC mode (free, read-only: CT subdomains -> DNS -> AWS ip-ranges + ASN)
// per lead, concurrently. Writes a full report to _deeprescan_out.json. NO DB writes here (anon can't);
// the parent applies upgrades via service-role SQL from the report. Candidates embedded (snapshot).
// Run:  node _deeprescan.mjs
import fs from "node:fs";
const SRC = fs.readFileSync("src/forge.jsx", "utf8");
const BASE = "https://nvjizahtcqgmfhiodtej.supabase.co";
const ANON = (SRC.match(/anonKey:\s*\n?\s*"([^"]+)"/) || [])[1];
const CONC = 6;

const CANDS = [
{id:"19e700817ef9tn6qg",domain:"sfv.se"},{id:"19e700817f0c8ydpv",domain:"partillebo.se"},{id:"19e700817eeoa7wlw",domain:"akademiskahus.se"},{id:"19e700817f0x12ihh",domain:"rikshem.se"},{id:"19e700817ef8woo81",domain:"fastpartner.se"},{id:"19e700817f0lp6mdu",domain:"service.se"},{id:"19e700817eei1d1oz",domain:"cbre.se"},{id:"19e700817f0p6xcyp",domain:"bjurfors.se"},{id:"19e700817efz44fj4",domain:"locum.se"},{id:"19e700817f0148mri",domain:"stenafastigheterstockholm.se"},{id:"19e700817efcmiv8l",domain:"wihlborgs.se"},{id:"19e700817eeuddrxw",domain:"corempropertygroup.se"},{id:"19e700817f0zk9r19",domain:"svefa.se"},{id:"19e700817efouzobj",domain:"icafastigheter.se"},{id:"19e700817eea5loef",domain:"luotea.se"},
{id:"nn-nibe.se",domain:"nibe.se"},{id:"imp-8d1862573ace",domain:"stronger.se"},{id:"imp-67c2dcddf60b",domain:"idealofsweden.com"},{id:"imp-047e2e3ed00e",domain:"bokio.se"},{id:"imp-c3e48ee0e7b8",domain:"chimivision.com"},{id:"nn-svnty.com",domain:"svnty.com"},{id:"nn-skanska.co.uk",domain:"skanska.co.uk"},{id:"imp-5e272ac698fa",domain:"boozt.com"},{id:"nn-trioworld.com",domain:"trioworld.com"},{id:"imp-1ca4d532b56b",domain:"benify.com"},{id:"imp-77d9efe557d6",domain:"outnorth.com"},{id:"imp-bbe08368b8b4",domain:"babyshop.com"},{id:"imp-ac8fe375b5c0",domain:"desenio.com"},{id:"imp-97b0a59104ac",domain:"depict.ai"},{id:"imp-aec7e8dacae7",domain:"royaldesign.se"},{id:"nn-novozymes.com",domain:"novozymes.com"},{id:"nn-veidekke.no",domain:"veidekke.no"},{id:"nn-mtr.se",domain:"mtr.se"},{id:"imp-32626c661bf2",domain:"kicks.se"},{id:"imp-5ffc7ce5aea2",domain:"mynewsdesk.com"},{id:"nn-tiohundra.se",domain:"tiohundra.se"},{id:"imp-df9ed3866b18",domain:"skincity.com"},{id:"imp-bfe55e88426f",domain:"teknikmagasinet.se"},{id:"imp-de71a16722f2",domain:"rule.io"},{id:"nn-planmeca.com",domain:"planmeca.com"},{id:"nn-nsm.no",domain:"nsm.no"},{id:"imp-e47a0f2ffbf1",domain:"centra.com"},{id:"imp-ba7a69afcb9e",domain:"kognity.com"},{id:"nn-rentokil-initial.com",domain:"rentokil-initial.com"},{id:"nn-reformcph.com",domain:"reformcph.com"},{id:"imp-b5a107da7299",domain:"nelly.com"},{id:"19e7004be17vtfmg6",domain:"jobylon.com"},{id:"19e7004be1732nuxa",domain:"corite.com"},{id:"nn-regeringskansliet.se",domain:"regeringskansliet.se"},{id:"imp-376f8cca142b",domain:"bubbleroom.se"},{id:"imp-d9241fa7c368",domain:"bannerflow.com"},{id:"19e7004be17pksgip",domain:"gilion.com"},{id:"nn-flokk.com",domain:"flokk.com"},{id:"nn-granges.com",domain:"granges.com"},{id:"nn-logisnext.eu",domain:"logisnext.eu"},{id:"imp-0c5adc510637",domain:"webhallen.com"},{id:"nn-mycronic.com",domain:"mycronic.com"},{id:"imp-49c938ed7f9a",domain:"netigate.net"},{id:"nn-vaasan.fi",domain:"vaasan.fi"},{id:"nn-anicura.se",domain:"anicura.se"},{id:"nn-solstad.com",domain:"solstad.com"},{id:"nn-matas.dk",domain:"matas.dk"},{id:"imp-cabda7c4e9cc",domain:"matsmart.se"},{id:"nn-hhs.se",domain:"hhs.se"},{id:"nn-ranagruber.no",domain:"ranagruber.no"},{id:"nn-saxobank.com",domain:"saxobank.com"},{id:"nn-protan.no",domain:"protan.no"},{id:"nn-erst.dk",domain:"erst.dk"},{id:"nn-hkscan.com",domain:"hkscan.com"},{id:"nn-lkab.com",domain:"lkab.com"},{id:"nn-kirkbi.com",domain:"kirkbi.com"},{id:"imp-d6d67f5e0353",domain:"hmgroup.com"},{id:"nn-stenarecycling.se",domain:"stenarecycling.se"},{id:"nn-thomasbetong.se",domain:"thomasbetong.se"},{id:"imp-66d86d4f3cd1",domain:"kive.ai"},{id:"imp-32e21e03e90f",domain:"oddmolly.com"},{id:"nn-boreal.no",domain:"boreal.no"},{id:"patch-smartcraft",domain:"smartcraft.com"},
{id:"19e700817ef96wr1z",domain:"hugebostader.se"},{id:"19e700817f0y1mrxn",domain:"arc.se"},{id:"19e700817ef9jlb9p",domain:"fastighetsagarna.se"},{id:"19e700817f0p0gq8y",domain:"bostad.stockholm.se"},{id:"19e700817efndxfpv",domain:"cemi.se"},{id:"19e700817eesv6fan",domain:"krambo.se"},{id:"19e700817eer2fjv2",domain:"lkf.se"},{id:"19e700817efqfk67h",domain:"citycon.com"},{id:"19e700817eecx6bhh",domain:"svenskabostader.se"},{id:"19e700817efjktgxw",domain:"tunabyggen.se"},{id:"19e700817efvcjm7c",domain:"hig.se"},{id:"19e700817f0g47jwl",domain:"alvstrandenutveckling.se"},{id:"19e700817efbrpqgf",domain:"vasbyhem.se"},{id:"19e700817f0ca2nba",domain:"magnoliautveckling.se"},{id:"19e700817efyv5e6h",domain:"dios.se"},{id:"19e700817f1fx8zvg",domain:"willhem.se"},{id:"19e700817eepso49e",domain:"stockholmshem.se"},{id:"19e700817efggt5hd",domain:"futurumfastigheter.se"},{id:"19e700817f1rg9nft",domain:"humlegardenfastigheter.se"},{id:"19e700817eekluj4j",domain:"bostadsbolaget.se"},{id:"19e700817efho7uhe",domain:"allbohus.se"},{id:"19e700817f09d5bgs",domain:"gladahudikhem.se"},{id:"19e700817efoxsziv",domain:"vatterhem.se"},{id:"19e700817f03akix0",domain:"platzerfastigheter.se"},{id:"19e700817f06o3qfq",domain:"crendo.se"},{id:"19e700817efxwnlfm",domain:"kopparstaden.se"},{id:"19e700817eeo567fs",domain:"poseidon.goteborg.se"},{id:"19e700817efj046fb",domain:"sigtunahem.se"},{id:"19e700817efd8hqxx",domain:"fabo.se"},{id:"19e700817eeald8gs",domain:"bostader.boras.se"},{id:"19e700817ee0py5jn",domain:"kfast.se"},{id:"19e700817ef18rbqw",domain:"hfab.se"},{id:"19e700817f0jb34cv",domain:"lulebo.se"},{id:"19e700817efaihum1",domain:"fastighetsforvaltaren.se"},{id:"19e700817f0hp8r1d",domain:"eksjobostader.se"},{id:"19e700817ef5lct1n",domain:"fortifikationsverket.se"},{id:"19e700817efer9eke",domain:"arvikafastighet.se"},{id:"19e700817eev3s6s1",domain:"familjebostader.se"},{id:"19e700817ee7x6r7w",domain:"tierpsbyggen.se"},{id:"19e700817efklyo2i",domain:"hyresbostaderinorrkoping.se"},{id:"19e700817f0ly1evc",domain:"bredablickforvaltning.se"},
{id:"imp-4b2ff48422e6",domain:"adlibris.com"},{id:"nn-assaabloy.com",domain:"assaabloy.com"},{id:"nn-stromma.com",domain:"stromma.com"},{id:"nn-danskebank.com",domain:"danskebank.com"},{id:"nn-teliasonera.com",domain:"teliasonera.com"},{id:"nn-smhi.se",domain:"smhi.se"},{id:"nn-nespresso.com",domain:"nespresso.com"},{id:"nn-arvato.com",domain:"arvato.com"},{id:"nn-swedbank.se",domain:"swedbank.se"},{id:"nn-cargotec.com",domain:"cargotec.com"},{id:"nn-subsea7.com",domain:"subsea7.com"},{id:"nn-lansforsakringar.se",domain:"lansforsakringar.se"},{id:"imp-57d37af0f6b3",domain:"stadium.se"},{id:"nn-bakerhughes.com",domain:"bakerhughes.com"},{id:"nn-elisa.com",domain:"elisa.com"},{id:"nn-skandia.se",domain:"skandia.se"},{id:"nn-jysk.com",domain:"jysk.com"},{id:"nn-kongsberg.com",domain:"kongsberg.com"},{id:"nn-orkla.se",domain:"orkla.se"},{id:"imp-fd9c9c9125fe",domain:"winningtemp.com"},{id:"nn-serneke.se",domain:"serneke.se"},{id:"nn-worldline.com",domain:"worldline.com"},{id:"nn-maersk.com",domain:"maersk.com"},{id:"nn-itella.com",domain:"itella.com"},{id:"imp-99732b78333a",domain:"happysignals.com"},{id:"nn-turku.fi",domain:"turku.fi"},{id:"imp-a9a19bdae636",domain:"cervera.se"},{id:"nn-skistar.com",domain:"skistar.com"},{id:"nn-swedbank.com",domain:"swedbank.com"},{id:"nn-internetstiftelsen.se",domain:"internetstiftelsen.se"},{id:"imp-ee8b0add8a38",domain:"upsales.com"},{id:"imp-c06f709e3283",domain:"humly.com"},{id:"nn-leroy.no",domain:"leroy.no"},{id:"imp-0591d2b7c8b3",domain:"polarnopyret.com"},{id:"imp-55a2424e6b17",domain:"pinmeto.com"},{id:"nn-fresenius-kabi.com",domain:"fresenius-kabi.com"},{id:"nn-elisa.fi",domain:"elisa.fi"},{id:"imp-8d0f48067afd",domain:"scandinavianphoto.se"},{id:"imp-ce74db058bbd",domain:"hopsworks.ai"},{id:"imp-90870bd2826b",domain:"pagero.com"},{id:"imp-0cc27bb49dc4",domain:"lyko.com"},{id:"nn-uppsala.se",domain:"uppsala.se"},{id:"nn-elanders.com",domain:"elanders.com"},{id:"nn-dnb.no",domain:"dnb.no"},{id:"imp-694f8acb2231",domain:"komplett.se"},{id:"nn-loomis.com",domain:"loomis.com"},{id:"nn-volvo.com",domain:"volvo.com"},{id:"nn-ica.se",domain:"ica.se"},{id:"nn-norgesgruppen.no",domain:"norgesgruppen.no"},{id:"nn-fbdata.se",domain:"fbdata.se"},{id:"19e7004be17tlh2zm",domain:"coursio.com"},{id:"imp-8e1e25c9a32c",domain:"flowhaven.com"},{id:"nn-scania.com",domain:"scania.com"},
{id:"19e700817f0objrg3",domain:"strangnasfastighets.se"},{id:"19e700817f0pi5ud3",domain:"shurgardsweden.se"},{id:"19e700817f06vmquc",domain:"stenafastighetermalmo.se"},{id:"19e700817f0lyypq8",domain:"kustbostaderioxelosund.se"},{id:"19e700817f0jysycr",domain:"kommunfastigheterilaholm.se"},{id:"19e700817ef3v63tz",domain:"axcellfastighetspartner.se"},{id:"19e700817efvw4cjo",domain:"telgefastigheter.se"},{id:"19e700817f0682yc7",domain:"primarfastighetsforvaltning.se"},{id:"19e700817efk30xag",domain:"kirunostader.se"},{id:"19e700817ef7h4joq",domain:"nogroup.se"},{id:"19e700817f0de9hq0",domain:"neoboservice.se"},{id:"19e700817f17t4mhu",domain:"novierrealestate.se"},{id:"19e700817f0f0100v",domain:"vasterviksbostads.se"},{id:"19e700817efr5oppn",domain:"micasafastigheteristockholm.se"},{id:"19e700817f0oog0n4",domain:"kopingsbostads.se"},{id:"19e700817f0uafu5d",domain:"varbergsbostads.se"},{id:"19e700817efw95ro9",domain:"marksbostads.se"},{id:"19e700817f1ax4r5s",domain:"morbylangabostads.se"},{id:"19e700817efxp0v4p",domain:"huddingesamhallsfastigheter.se"},{id:"19e700817ef4dz107",domain:"karlstadsbostads.se"},{id:"19e700817efoasgxs",domain:"telgebostader.se"},{id:"19e700817f0w3fs9q",domain:"sveafastigheterservices.se"},{id:"19e700817f0ro0bbv",domain:"stenafastighetergoteborg.se"},{id:"19e700817f0senh64",domain:"solatumhushem.se"},{id:"19e700817efiyrkri",domain:"ludvikakommunfastigheter.se"},
{id:"imp-d173f338a3a1",domain:"hibox.tv"},{id:"nn-se.abb.com",domain:"se.abb.com"},{id:"imp-e42b28af42f9",domain:"varjo.com"}
];

const norm = (d) => String(d || "").toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/.*$/, "");
async function scan(domain) {
  try {
    const r = await fetch(BASE + "/functions/v1/cloud-detect", {
      method: "POST", headers: { "Content-Type": "application/json", Authorization: "Bearer " + ANON, apikey: ANON },
      signal: AbortSignal.timeout(90000), body: JSON.stringify({ domains: [norm(domain)] }),
    });
    const j = await r.json();
    return (j.report || [])[0] || { provider: "error", error: j.error || ("http " + r.status) };
  } catch (e) { return { provider: "error", error: String(e.message || e).slice(0, 60) }; }
}

const out = [];
let done = 0, upg = 0;
const queue = [...CANDS];
async function worker() {
  while (queue.length) {
    const c = queue.shift();
    const rep = await scan(c.domain);
    const up = ["aws", "gcp", "azure"].includes(rep.provider) && rep.confidence && rep.confidence !== "none";
    if (up) upg++;
    const row = { id: c.id, domain: c.domain, provider: rep.provider, confidence: rep.confidence || "", services: rep.services || [], asns: rep.asns || [], ct: rep.ct_count || 0, upgrade: up };
    out.push(row);
    done++;
    if (up) console.log(`  ★ ${c.domain} -> ${rep.provider.toUpperCase()} (${rep.confidence}) ${(rep.services||[]).join("/")} ${done}/${CANDS.length}`);
    else if (done % 15 === 0) console.log(`  ...${done}/${CANDS.length} (${upg} upgrades so far)`);
    if (done % 20 === 0) fs.writeFileSync("_deeprescan_out.json", JSON.stringify({ done, total: CANDS.length, upgrades: upg, results: out }, null, 1));
  }
}
console.log(`Deep re-scan: ${CANDS.length} hidden-origin leads, concurrency ${CONC}`);
await Promise.all(Array.from({ length: CONC }, worker));
fs.writeFileSync("_deeprescan_out.json", JSON.stringify({ done, total: CANDS.length, upgrades: upg, done_flag: true, results: out }, null, 1));
const byProv = out.reduce((m, r) => ((m[r.provider] = (m[r.provider] || 0) + 1), m), {});
console.log(`=== DONE === ${done} scanned | ${upg} upgrades to a compute cloud | provider tally: ${JSON.stringify(byProv)}`);
console.log("UPGRADES:");
for (const r of out.filter((x) => x.upgrade)) console.log(`  ${r.domain}\t${r.provider}\t${r.confidence}\t${r.services.join("/")}\tASN ${r.asns.slice(0,3).join(",")}`);
