UPDATE companies c SET cloud_provider=v.np, aws_detected=(v.np='aws'), aws_signals=v.sig, enrichment=COALESCE(c.enrichment,'{}'::jsonb)||jsonb_build_object('cloud_reaudit_at',now()::text) FROM (VALUES
('nn-anicura.se','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('19e700817eeqq2tct','other','Non-hyperscaler host (apex other, ASN 41848) — re-audited; prior azure was a stray asset/IP match'),
('19e700817f0p0gq8y','other','Non-hyperscaler host (apex other, ASN 29672) — re-audited; prior azure was a stray asset/IP match'),
('19e7004be17tlh2zm','other','Non-hyperscaler host (apex other, ASN 14061) — re-audited; prior aws was a stray asset/IP match'),
('19e7004be1732nuxa','gcp','GCP · apex cloudflare · low (re-audited, apex-anchored) (ASN 13335,396982)'),
('nn-deepoceangroup.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('nn-erst.dk','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior azure was a stray asset/IP match)'),
('19e700817ef9jlb9p','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior azure was a stray asset/IP match)'),
('nn-flex.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('imp-d6d67f5e0353','other','Non-hyperscaler host (apex other, ASN 16625) — re-audited; prior azure was a stray asset/IP match'),
('19e700817eekluj4j','other','Non-hyperscaler host (apex other, ASN 25387) — re-audited; prior azure was a stray asset/IP match'),
('imp-d173f338a3a1','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('nn-hkscan.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior azure was a stray asset/IP match)'),
('nn-hhs.se','other','Non-hyperscaler host (apex other, ASN 42708) — re-audited; prior aws was a stray asset/IP match'),
('imp-c06f709e3283','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior gcp was a stray asset/IP match)'),
('imp-32626c661bf2','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('nn-loomis.com','other','Non-hyperscaler host (apex other, ASN 214302) — re-audited; prior aws was a stray asset/IP match'),
('19e700817eer2fjv2','other','Non-hyperscaler host (apex other, ASN 197332) — re-audited; prior azure was a stray asset/IP match'),
('imp-49c938ed7f9a','other','Non-hyperscaler host (apex other, ASN 202053) — re-audited; prior aws was a stray asset/IP match'),
('nn-metsagroup.com','azure','AZURE · apex cloudflare · low (re-audited, apex-anchored) (ASN 30811,13335,8075)'),
('nn-planmeca.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior azure was a stray asset/IP match)'),
('nn-rentokil-initial.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('19e700817f0x12ihh','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior azure was a stray asset/IP match)'),
('nn-scania.com','other','Non-hyperscaler host (apex other, ASN 54113) — re-audited; prior aws was a stray asset/IP match'),
('imp-df9ed3866b18','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior gcp was a stray asset/IP match)'),
('imp-de71a16722f2','other','Non-hyperscaler host (apex other, ASN 16276) — re-audited; prior aws was a stray asset/IP match'),
('nn-leroy.no','other','Non-hyperscaler host (apex other, ASN 8542) — re-audited; prior aws was a stray asset/IP match'),
('imp-e42b28af42f9','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('nn-vaxjo.se','other','Non-hyperscaler host (apex other, ASN 41174) — re-audited; prior aws was a stray asset/IP match'),
('19e700817f1fx8zvg','other','Non-hyperscaler host (apex other, ASN 57208) — re-audited; prior azure was a stray asset/IP match'),
('nn-volvo.com','other','Non-hyperscaler host (apex other, ASN 25252) — re-audited; prior aws was a stray asset/IP match'),
('nn-yara.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('nn-yit.fi','azure','AZURE · apex cloudflare · low (re-audited, apex-anchored) (ASN 30811,13335,8075)'),
('nn-inwido.com','cloudflare','Behind Cloudflare — origin not confirmed on a cloud (re-audited; prior aws was a stray asset/IP match)'),
('nn-zenitel.com','other','Non-hyperscaler host (apex other, ASN 16276) — re-audited; prior aws was a stray asset/IP match')
) AS v(id,np,sig) WHERE c.id=v.id;